const DOMAIN_MAP: Record<string, string> = {
  RELIANCE: 'ril.com',
  TCS: 'tcs.com',
  HDFCBANK: 'hdfcbank.com',
  INFY: 'infosys.com',
  ICICIBANK: 'icicibank.com',
  HINDUNILVR: 'hul.co.in',
  ITC: 'itcportal.com',
  SBIN: 'sbi.co.in',
  BHARTIARTL: 'airtel.in',
  KOTAKBANK: 'kotak.com',
  LT: 'larsentoubro.com',
  BAJFINANCE: 'bajajfinserv.in',
  AXISBANK: 'axisbank.com',
  MARUTI: 'marutisuzuki.com',
  TATAMOTORS: 'tatamotors.com',
  SUNPHARMA: 'sunpharma.com',
  TITAN: 'titan.co.in',
  ASIANPAINT: 'asianpaints.com',
  WIPRO: 'wipro.com',
  HCLTECH: 'hcltech.com',
  ULTRACEMCO: 'ultratechcement.com',
  NESTLEIND: 'nestle.in',
  POWERGRID: 'powergrid.in',
  NTPC: 'ntpc.co.in',
  ONGC: 'ongcindia.com',
  TECHM: 'techmahindra.com',
  TATASTEEL: 'tatasteel.com',
  ADANIENT: 'adani.com',
  BAJAJFINSV: 'bajajfinserv.in',
  COALINDIA: 'coalindia.in',
  DRREDDY: 'drreddys.com',
  DIVISLAB: 'divislaboratories.com',
  CIPLA: 'cipla.com',
  HEROMOTOCO: 'heromotocorp.com',
  EICHERMOT: 'eicher.in',
  BRITANNIA: 'britannia.co.in',
  APOLLOHOSP: 'apollohospitals.com',
  JSWSTEEL: 'jsw.in',
  INDUSINDBK: 'indusind.com',
  GRASIM: 'grasim.com',
  BPCL: 'bharatpetroleum.in',
  HINDALCO: 'hindalco.com',
  SBILIFE: 'sbilife.co.in',
  HDFCLIFE: 'hdfclife.com',
  BAJAJ_AUTO: 'bajajauto.com',
  TATACONSUM: 'tataconsumer.com',
  M_M: 'mahindra.com',
};

export function getStockLogoUrl(symbol: string): string | null {
  const domain = DOMAIN_MAP[symbol.toUpperCase()];
  if (!domain) return null;
  return `https://logo.clearbit.com/${domain}`;
}
